### ISSUE TITLE
forwarding by moving slider doesn't work

### ISSUE THREAD

**Issue by derede** [gateship-one/malp#97]
minor problem:
forwarding inside an audio file by moving the slider doesn't work for me. Played time is updated but audio is muted. Can be annoying on longer soundfiles (audio books).

BTW: A big loud THANKS for M.A.L.P.!

**Comment by gnome17** [comment]
Should be fixed with the new released version. If not please repoen this issue

**Comment by derede** [comment]
Sorry, still doesn't work as expected. Tried with mp3: time is updated but sound doesn't work or just plays further without jumping but false time stamp...
